defaults: &defaults
  adapter: mysql2
  encoding: utf8
  username: root
  password:
  host: localhost
  reconnect: true

development:
  <<: *defaults
  database: grow_web_development

test:
  <<: *defaults
  database: grow_web_test
